# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "gsearch-parser"
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Diego Netto"]
  s.date = "2012-04-11"
  s.description = "Queries Google search and parses the resulting web page for content."
  s.email = "diegormnetto@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "gsearch-parser.gemspec",
    "lib/gsearch-parser.rb",
    "lib/gsearch-parser/version.rb"
  ]
  s.homepage = "https://github.com/diegonetto/gsearch-parser"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.21"
  s.summary = "Google search result parser."

end

